#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
set -e

for app in src/foamToNumpy src/numpyToFoam
do
    echo "Cleaning ${app}..."
    (cd "${app}" && wclean)
done

#------------------------------------------------------------------------------
