#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
set -e

for app in \
    src/functionObjects/foamToNumpy \
    src/numpyPostProcess \
    src/foamToNumpy \
    src/numpyToFoam
do
    echo "Building ${app}..."
    (cd "${app}" && wmake)
done

#------------------------------------------------------------------------------
